### ISSUE TITLE
Add some information for Repository

### ISSUE THREAD

**Issue by HaiDang2001VN** [omair18/LSD-SLAM-Android#1]
@omair18 , thank you for an excited transformation of LSD-SLAM into Android with all dependencies included.
I am going to use some part of this code (the prebuilt included and C++ files in JNI folder), so I will very pleasure if you add your LICENSE file to indicate the usage condition.
Also, in the `buildscript: repositories` part of `build.gradle` file, it is necessary to add `google()` to include Google Maven, [allowing](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration) to use Gradle 3.0.1 with distributionUrl is Gradle 4.1 (as specified by you).
Beside that, I see the [libLSD.so](https://github.com/omair18/LSD-SLAM-Android/blob/master/app/src/main/libs/armeabi-v7a/libLSD.so) has already been in the repository, though the NOTE indicated that it hasn't. Does this file was uncompletely built or that README's line is outdated?
Thanks in advance.

**Comment by omair18** [comment]
@HaiDang2001VN I have corrected the README. libLSD.so was correctly built for both architectures. I'm sure it'd work without the need of recompilation. 
Google Maven was automatically suggested by Android Studio so I didn't include it in dependencies.

**Comment by HaiDang2001VN** [comment]
Thank you very much for fast reply and the awesome contribution @omair18 .
